### PR TITLE
emoji: auto-generate definitions from Unicode data files

### PR DESCRIPTION
**Pull request by apjanke**
Refactors the emoji plugin to programmatically generate its emoji-data code from source files, instead of hand-coding it. Adds a bit of other stuff.

This is a sub-PR (or whatever you call it) for robbyrussell/oh-my-zsh#2446: the intention is that merging this PR will pull these changes in to that existing PR. (Let me know if I didn't set this up right to do that.)

Adds a script to auto-generate the zsh character definition stuff from Unicode source data files.
Adds a README.
Refactors the functions and group listings to have fewer functions, but have them take group names as parameters.
Pull group definitions in to a single associative array to conserve namespace, and allow definition of custom groups by users at run time.
Adds country flags for various countries, identified by country name.
Adds experimental support for skin tone diversity.

### CODE REVIEW

**Comment by fallwith** [comment]
Hello @apjanke - thanks very much for putting this together. I like the improvements; including the extra tweaks that were done in addition what we discussed previously. Cool stuff!

I only have one small change that I'd like to see done to `emoji-char-definitions.zsh`. The keys on lines 1052, 1063, 1081, and 1251 contain non-ascii characters that would make them difficult to use. It looks like your `update_emoji.pl` script is already converting some characters to underscores. Could you please update it to also convert the characters on those lines to underscores and re-generate the .zsh file?

**Comment by apjanke** [comment]
Thank you!

I'm totally open to discussing the non-ASCII character thing with nation names. But I think we might want to keep those. I intentionally preserved them in the script (by using `\p{Letter}` instead of `\w` or whatever), because I think people might be using them. Emoji themselves are non-ASCII, and their use sort of presumes that you're in a Unicode locale. So I think we can use Unicode letters here. In the good case, international users with well-configured locales and modern terminal emulators can use the accented characters; in the worst case, ASCII-only users get unreadable junk for languages they don't care about anyway.

Consider the case of line 1052, `Ã_land_Islands`. If you actually want to use this nation's flag, and you have your terminal and environment set up right, you might be able to type `$emoji_flags[` and then `A` and press tab, and it might autocomplete. And it's more readable in the output. I think that's more useful than just crushing it to `__land_Islands`.

Zsh itself is Unicode-aware and fine with these strings as keys (I think, as long as your locale isn't busted). It's more of a user presentation and quoting matter.

If we're going to crush it to ASCII, we should probably just strip accents (e.g. convert `"Ã"` to`"A"`) instead of doing a blanket conversion to underscores. Because of how UTF-8 and UTF-16 are defined, I don't think there are any cases where a misconfigured locale would cause non-ASCII Unicode characters to devolve to anything syntactically significant to `zsh`.

**Comment by fallwith** [comment]
That logic sounds good to me. Thanks for explaining why it was a deliberate choice to preserve the accents.

**Comment by apjanke** [comment]
Sweet! Thank you.

**Pull request merged**
